<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MS-20160625LRRB" ignored="0" name="Test" tests="3" failures="1" timestamp="03 十一月 2017 17:44:02 GMT" time="0.234" errors="0">
  <testcase name="add" time="0.14" classname="com.cn.AddTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [6]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [6]
	at com.cn.AddTest.add(AddTest.java:23)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- add -->
  <testcase name="add" time="0.0" classname="com.cn.AddTest"/>
  <testcase name="add" time="0.0" classname="com.cn.AddTest"/>
</testsuite> <!-- Test -->
